### ISSUE TITLE
second bracket popping up

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neopairs.vim#2]
First have both neopairs and neco-vim enabled. Then open a empty buffer. Set its filetype to vim. Then just type in `L`, then `(` and then `)` with insert mode.

For some reason a second bracket pops up after the last bracket.

**Comment by Shougo** [comment]
Fixed.

**Comment by nhooyr** [comment]
@Shougo I got this problem again but now if I type `system("`. 2 brackets pop up after the `"`.

**Comment by Shougo** [comment]
Fixed again.

**Comment by nhooyr** [comment]
@Shougo happening again with the following (cursor is at `|`)

`eval(|)`

Enter insert mode between the two brackets and then leave, second bracket appears.

**Comment by Shougo** [comment]
I will check it later.

**Comment by Shougo** [comment]
Fixed.
