### ISSUE TITLE
How neopairs works?

### ISSUE THREAD

**Issue by pablox-cl** [Shougo/neopairs.vim#3]
From what I understand, neopairs can close parenthesis after "completedone", but it doesn't say how it does it or if I need another plugin.

I open a vim file, write:

``` vim
expand('|
" `|` is the cursor location
expand('$DIR/ " press esc
```

I expected to close the parenthesis, or by pressing tab, but none of them works. Can you give me a minimal example to try it out?

**Comment by Shougo** [comment]
This is not supported.
Closing.
It works just you want to insert function name.
Not function arguments.

**Comment by pablox-cl** [comment]
Sorry, I think I don't understand how it works. Can you give me a short example?

**Comment by Shougo** [comment]
neopairs.vim works only function name completion like `expand(` to `expand(|)`.
`|` is cursor.

**Comment by pablox-cl** [comment]
But when neopairs would actually add the closing parenthesis?

**Comment by Shougo** [comment]
> But when neopairs would actually add the closing parenthesis? 

neopairs not general closing parenthesis plugin.
It works in the completion only(again).

If you need general closing parenthesis plugin, you should use other plugins.

**Comment by pablox-cl** [comment]
I understand that :). But neopairs doesn't seem to expand anything, can you give me a simple working example to test the plugin is working?

**Comment by Shougo** [comment]
Sorry, I have not the time.

**Comment by pablox-cl** [comment]
Ok, I understand, but I was referring to a short narrative about how it's used, because I don't understand what it does, if one is already using deoplete, or neocomplete.

**Comment by nhooyr** [comment]
@PaBLoX-CL type `echo exp` in a vim file. if you complete on expand normally, you get `echo expand(|`, but with neopairs.vim, the end result is `echo expand(|)`.
